import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
// import 'mermaid/dist/mermaid.css';
import NavBar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import ThemeProvider from "@/components/providers/theme_provider";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={true}
          disableTransitionOnChange={true}
        >
          <NavBar />
          <div className="mx-auto">
            {children}
            <SpeedInsights />
            <Analytics />
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
