import type { Metadata } from "next";
import {
  Inter,
  Nanum_Myeongjo,
  Noto_Serif,
  Source_Serif_4,
} from "next/font/google";
import "./globals.scss";
// import 'mermaid/dist/mermaid.css';
import NavBar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import ThemeProvider from "@/components/providers/theme_provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={true}
          disableTransitionOnChange={true}
        >
          <NavBar />
          <div className="mx-auto">{children}</div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
